### ISSUE TITLE
点击标题链接后，导航菜单就再次不工作。

### ISSUE THREAD

**Issue by tcdw** [tcdw/optica-ghost#1]
但点击其它链接可以恢复。

**Comment by CaiJimmy** [comment]
我认为你既然把整个body都加载了，那就没有必要使用PJAX。应该使用InstantClick，同样是全页面加载，但是脚本不会失效。

另一个选项是修改主题的DOM布局，布局没有搞好，AJAX很麻烦。

**Comment by tcdw** [comment]
我想到了一个拙劣的方案，就是每次 ajax 后都通过 JS 重新加载头图，然后把加载地址放到容器里。
InstantClick 考虑过，但不太想用。

**Comment by CaiJimmy** [comment]
头部你可以通过style标签来修改背景（如果你不想加载的话）

我指的是菜单那些不会变的元素，完全没有必要二次加载。

**Comment by tcdw** [comment]
对，我也是想的不重新加载头部和菜单。

**Comment by CaiJimmy** [comment]
可以关闭这个issue了

**Comment by tcdw** [comment]
不错，在我博客上工作很出色。
有劳了。
