### ISSUE TITLE
文章页面出现故障

### ISSUE THREAD

**Issue by tcdw** [tcdw/optica-ghost#5]
在 Chrome 浏览器通过列表页打开文章页时滑动会卡住，同时菜单再次出现打不开的问题。
目前考虑先把 ajax 完成后的滑动特效去掉然后在逐步 debug，或者实在不行去除 pjax。

**Comment by CaiJimmy** [comment]
由于执行disqus.reset时embed.js尚未加载导致脚本错误。

解决方法
  - 在头部加载`embem.js`
  - JS判断是否存在`DISQUS.reset`

**Comment by tcdw** [comment]
经过一番纠结，最后把菜单放回了 pjax 容器里，然后问题解决。
